server:
  port: 8080

thymeleaf:
  prefix: classpath:/templates/
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/emp_dept?serverTimezone=UTC
    username: root
    password: 123qweasdzxc!@#QWEASDZXC
    jdbc.driverClass: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboottest1.entity
  initialization-mode: always
